import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/font.css";
import Script from "next/script";
import { GoogleTagManager } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
<Script async src="https://www.googletagmanager.com/gtag/js?id=G-DTPWL0BQD2"></Script>
<Script id="google-analytics">
  {`  window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-DTPWL0BQD2');
      `
    }
</Script>
      </head>
      <body>{children}
      <GoogleTagManager gtmId="GTM-NPCLFNHG"/>
      </body>
    </html>
  );
}
